name: CI

on: [push]

jobs: 
  build-ios:
    runs-on: macOS-10.15
    steps:
        - uses: actions/checkout@v1
        # - name: Install gpg
          # run:  brew install gnupg
        - name: Switch XCode Version
          # run: sudo xcode-select -s /Applications/Xcode_11.4.app
          run: sudo xcode-select -s /Applications/Xcode_11.7.app
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - uses: actions/checkout@v1
        - name: Install dependencies
          run: yarn install
        - name: Install Cocoapods 
          run: gem install cocoapods

        - name: Install pod dependencies
          run: |
            cd ios
            pod install
          shell: bash
        - name: Setup provisioning profile
          run: ./.github/secrets/decrypt_secrets.sh
          env:
            IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
        # - uses: yukiarrr/ios-build-action@v1.2.0 
        #   with:
        #     project-path: ./ios/ActionsTest.xcodeproj
        #     p12-base64: ${{ secrets.P12_BASE64 }}
        #     mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        #     code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        #     team-id: ${{ secrets.TEAM_ID }}
        #     scheme: ActionsTest
        #     export-method: enterprise
        #     output-path: ./ios/build/ActionsTest.ipa
        #     workspace-path: ./ios/ActionsTest.xcworkspace # optional
 

            # certificate-password: ${{ secrets.CERT_PASSWORD }}
        - name: Build app
          run: | 
            cd ios && xcodebuild -workspace ThreeDViews.xcworkspace \
            -scheme ThreeDViews -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/ThreeDViews.xcarchive
          env:
            IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
            # IPHONEOS_DEPLOYMENT_TARGET: 10.0 
        - name: Export app 
          run: |
            cd ios && xcodebuild -exportArchive -archivePath $PWD/build/ThreeDViews.xcarchive \
            -exportOptionsPlist ThreeDViews/Info.plist -exportPath $PWD/build
        - name: Run Webhook
          run: |
            curl -F "file=@../ios/build/ThreeDViews.ipa" -X POST  https://291f3ae855ba.ngrok.io/mobilebuild/webhook/callback/5f8eab89c7105e1b1cf18acd
        # - uses: actions/upload-artifact@v2 
        #   with:    
        #     name: ActionsTest.ipa
        #     path: ./ios/build/ActionsTest.ipa
        # - uses: actions/checkout@master
        # - uses: shallwefootball/s3-upload-action@master
        #   with:
        #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
        #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        #     aws_bucket: ${{ secrets.AWS_BUCKET }}
        #     source_dir: ./ios/build/ActionsTest.ipa
        #     destination_dir: builds/ios/iOS.ipa

        #   xcodebuild -workspace ActionsTest.xcworkspace -configuration Debug -scheme ActionsTest -destination id=59F60AFA-F216-408D-8F21-B40D7E5CBE8D
